apiRules:
- exclude:
    uidRegex: ^Modding\.Patches\.*
    type: Namespace
- exclude:
    uidRegex: ^System\.Runtime\.CompilerServices
    type: Namespace
- exclude:
    uidRegex: ^MonoMod\.MonoModRules
    type: Type
